language: python

matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38

  - python: pypy3
    env: TOXENV=pypy3

  - python: 3.7
    env: TOXENV=docs

install:
- pip install -U tox codecov

script: tox

after_success:
- codecov

deploy:
  on:
    branch: master
    tags: true
    condition: "$TOXENV == py38"
    repo: ejulio/itemloaders
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: __token__
  password:
    secure: kB+4/yfvt2HXfZwFxVEtH2X/NeqrMrL7FW8Xzbl5t+GWWvyPg8igVOXMrgPIUqU5XXqFJxnEf+Z9MuiPyk8Dwv6EcpXikObMISrp4QI9o5pIoEEPSESv7mQ4LVGyEcQmEjxLn601o9E2FvtSdp6PIxXjm+JTqu12+6k6jUgrmBiwXGMK727fX0Jqo8u6tRsZ5MmqTjBniFzuWszPCGfjFzYThfdW36WJYVKtxlIf0Mp2/onJHfhIffiWukUTGlweFuuUH4WC0eTcKfOV+mxuw6B/fKoVxSJE1aYMrEBcNCNWXoD0H5DW/M8uvLtaCrWEm1KdSP0b7+AiHMxQhH2QJoGQS4sXDpAROqZWD1Oub+Pt98gkz6z6Iikrj60HuuyjyICgJ03q6PrWBv73zGoTRA60/QHytbySifWW4dUD0b40cfJJDbsN5ouTb2gCy52ZCFFmMO9bue1tMv6+djmcWcTTm5HXtiCDT7tnv6e1K6e6laEcSaWWuNEmWyE1YxgdvKl0xHrAYYa2h0V8ijH1jw4pEIXJThttHyWfwNsBo66ej9FdN38h7VYyh3qBr6qwNmQrk2yooN0sFWnoQVERUMZA/mz3XYQk6v1B7LawG6FGlkcpD+JpQMjMiHuKfjNoel8KH5DOZZmRM3rZorimvptTZSo2ZR2rk8fNGbKhXzc=
